require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'studyinglab' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  
  pod 'Firebase/Analytics'

  pod 'RNFS', :path => '../node_modules/react-native-fs'



  target 'studyinglabTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'studyinglab-tvOS' do
  # Pods for studyinglab-tvOS

  target 'studyinglab-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
